### ISSUE TITLE
图像理解api出错

### ISSUE THREAD

**Issue by Echo-jyt** [suqingdong/sparkapi#8]
您好，我调用图像理解api报这个错误是怎么回事呢   
 content = res['payload']['choices']['text'][0]['content']
KeyError: 'payload'

**Comment by suqingdong** [comment]
图像理解API服务申请了么？
https://console.xfyun.cn/sale/buy?wareId=9046&packageId=9046002&serviceName=%E5%9B%BE%E7%89%87%E7%90%86%E8%A7%A3&businessId=image
![image](https://github.com/user-attachments/assets/600716b5-0c6c-446d-8c61-bcca6875aebb)

**Comment by Echo-jyt** [comment]
谢谢大佬，后面我申请了就可以了


| |
Echo_jyt
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Qingdong ***@***.***> |
| 发送日期 | 2024年7月23日 10:23 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
State ***@***.***> |
| 主题 | Re: [suqingdong/sparkapi] 图像理解api出错 (Issue #8) |

图像理解API服务申请了么？
https://console.xfyun.cn/sale/buy?wareId=9046&packageId=9046002&serviceName=%E5%9B%BE%E7%89%87%E7%90%86%E8%A7%A3&businessId=image
image.png (view on web)

**Comment by suqingdong** [comment]
> 谢谢大佬，后面我申请了就可以了 | | Echo_jyt | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | Qingdong ***@***.***> | | 发送日期 | 2024年7月23日 10:23 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , State ***@***.***> | | 主题 | Re: [suqingdong/sparkapi] 图像理解api出错 (Issue #8) | 图像理解API服务申请了么？ https://console.xfyun.cn/sale/buy?wareId=9046&packageId=9046002&serviceName=%E5%9B%BE%E7%89%87%E7%90%86%E8%A7%A3&businessId=image image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

客气哈~
